excluded:
  - Pods
  - vendor

custom_rules:
    mark_spacing_after:
      included: ".*\\.swift"
      name: "Consistent MARK spacing"
      regex: "( +\/\/ MARK: [^\n]*\n^[^\n])"
      message: "Leave an empty line after a MARK declation."
      severity: warning

# Rule configurations
identifier_name:
  excluded:
    - id
    - x
    - y
    - z


disabled_rules:
  - force_cast


file_length: 500
line_length: 165
cyclomatic_complexity:
  warning: 10
type_name:
  max_length: 50
force_cast: warning
force_try: warning
function_parameter_count: 5
large_tuple:
  warning: 3
  error: 4
